# Render 자동 배포 설정 파일
services:
  - type: web
    name: chat-back
    env: python
    region: singapore  # 또는 oregon, frankfurt 등 원하는 리전
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    plan: starter  # 무료 티어, 또는 standard 등 유료 플랜 선택
    numInstances: 1
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        sync: false  # 수동 설정 필요
      - key: LANGGRAPH_API_URL
        sync: false  # 수동 설정 필요
      - key: LANGSMITH_API_KEY
        sync: false  # 수동 설정 필요
      - key: LANGSMITH_TRACING
        value: "true"
      - key: LANGCHAIN_PROJECT
        value: chat-production
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: true  # GitHub 연동 시 자동 배포
